### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by danutDiac**
Add project rules

### CODE REVIEW

**Review by andreicioromila — DISMISSED** [review]
Very good work! Keep it up!

**Review by iosifboanca — APPROVED** [review]
Approve

**Review by iosifboanca — APPROVED** [review]

**Review by MihaiBojescu — APPROVED** [review]

**Review by h-mihail — APPROVED** [review]

**Review by msal96 — APPROVED** [review]

**Review by MihaiBojescu — APPROVED** [review]
Approved.

**Review by h-mihail — APPROVED** [review]
I approve!

**Pull request merged**
